name: check build

on: [pull_request, push]

jobs:
  run_dune_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v2

      - name: Set up ocaml
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: 4.12.0

      - name: Make sure we can opam pin
        run: |
          opam pin add hexstring .
